language: node_js
node_js:
  - 8.9.0
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      - feedeo:jT8D0ItoxXQSUzFM1bfKEP2q
    on_success: never
    on_failure: never
    on_pull_requests: false
before_script:
  - npm prune
before_install:
  - npm config set //registry.npmjs.org/:_authToken \${NPM_TOKEN}
install:
  - npm install --"@feedeo:registry=https://registry.npmjs.org/"
after_success:
  - npm run coveralls
  - npm run semantic-release
